services:
  backend:
    build:
      context: ./backend
    container_name: movie_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: movie_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped