apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
      - name: frontend
        image: movie-booking-app-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
